nelmio_cors:
    paths:
        '^/auth':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
        '^/':
            origin_regex: true
            allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE']
            max_age: 3600
